import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Base64Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="m-10">
      {children}
    </section>
  );
}
